CREATE TABLE comment(
commentNo INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
boardNo INT NOT NULL,
content VARCHAR(1000) NOT NULL,
uid VARCHAR(30) NOT NULL,
reg_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
